CREATE TABLE USUARIOS (
    ID_USUARIO INT(3) NOT NULL,
    ID_DIRECCION INT(3) NOT NULL,
    ID_ROL INT(3) NOT NULL,
    NOMBRES VARCHAR(255) NOT NULL,
    AP_PATERNO VARCHAR(255) NOT NULL,
    AP_MATERNO VARCHAR(255) NOT NULL,
    F_NACIMIENTO DATE NOT NULL,
    TELEFONO INT(10) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CONSTRAINT ID_USUARIO_PK PRIMARY KEY (ID_USUARIO));

CREATE TABLE ROLES (
    ID_ROL INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_ROL_PK PRIMARY KEY (ID_ROL));

CREATE TABLE DIRECCIONES (
    ID_DIRECCION INT(3) NOT NULL,
    ID_MUNICIPIO INT(3) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    CP INT(5) NOT NULL,
    CONSTRAINT ID_DIRECCION_PK PRIMARY KEY (ID_DIRECCION));

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT(3) NOT NULL,
    ID_USUARIO INT(3) NOT NULL,
    ID_PRODUCTO INT(3) NOT NULL,
    CANTIDAD INT(4) NOT NULL,
    CONSTRAINT ID_PEDIDO_PK PRIMARY KEY (ID_PEDIDO));

CREATE TABLE MUNICIPIOS (
    ID_MUNICIPIO INT(3) NOT NULL,
    ID_ESTADO INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_MUNICIPIO_PK PRIMARY KEY (ID_MUNICIPIO));

CREATE TABLE ESTADOS (
    ID_ESTADO INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_ESTADO_PK PRIMARY KEY (ID_ESTADO));

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT(3) NOT NULL,
    ID_DIRECCION INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO INT(10) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT ID_PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR));

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT(3) NOT NULL,
    ID_PROVEEDOR INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    EXISTENCIA INT(4) NOT NULL,
    PRECIO FLOAT(6,2) NOT NULL,
    CONSTRAINT ID_PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO));

CREATE TABLE IMAGENES (
    ID_IMAGEN INT(3) NOT NULL,
    ID_PRODUCTO INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    SOURCE BLOB NOT NULL,
    CONSTRAINT ID_IMAGEN_PK PRIMARY KEY (ID_IMAGEN));

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS_DIRECCION
FOREIGN KEY (ID_DIRECCION)
REFERENCES DIRECCIONES(ID_DIRECCION);

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS_ROL
FOREIGN KEY (ID_ROL)
REFERENCES ROLES(ID_ROL);

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_USUARIOS
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIOS(ID_USUARIO);

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_PRODUCTOS
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTOS(ID_PRODUCTO);

ALTER TABLE PROVEEDORES
ADD CONSTRAINT FK_PROVEEDORES_DIRECCION
FOREIGN KEY (ID_DIRECCION)
REFERENCES DIRECCIONES(ID_DIRECCION);

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOS_PROVEEDORES
FOREIGN KEY (ID_PROVEEDOR)
REFERENCES PROVEEDORES(ID_PROVEEDOR);

ALTER TABLE DIRECCIONES
ADD CONSTRAINT FK_DIRECCIONES_MUNICIPIOS
FOREIGN KEY (ID_MUNICIPIO)
REFERENCES MUNICIPIOS(ID_MUNICIPIO);

ALTER TABLE MUNICIPIOS
ADD CONSTRAINT FK_MUNICIPIOS_ESTADO
FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADOS(ID_ESTADO);

ALTER TABLE IMAGENES
ADD FOREIGN KEY (ID_PRODUCTO) 
REFERENCES PRODUCTOS(ID_PRODUCTO);