CREATE TABLE USUARIOS (
    ID_USUARIO INT(3) NOT NULL AUTO_INCREMENT,
    ID_DIRECCION INT(3) NOT NULL,
    ID_ROL INT(3) NOT NULL,
    NOMBRES VARCHAR(255) NOT NULL,
    AP_PATERNO VARCHAR(255) NOT NULL,
    AP_MATERNO VARCHAR(255) NOT NULL,
    F_NACIMIENTO DATE NOT NULL,
    TELEFONO BIGINT(10) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    CONSTRAINT ID_USUARIO_PK PRIMARY KEY (ID_USUARIO));

CREATE TABLE ROLES (
    ID_ROL INT(3) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_ROL_PK PRIMARY KEY (ID_ROL));

CREATE TABLE DIRECCIONES (
    ID_DIRECCION INT(3) NOT NULL AUTO_INCREMENT,
    ID_LOCALIDAD INT(3) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    CP INT(5) NOT NULL,
    CONSTRAINT ID_DIRECCION_PK PRIMARY KEY (ID_DIRECCION));

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT(3) NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT(3) NOT NULL,
    ID_PRODUCTO INT(3) NOT NULL,
    CANTIDAD INT(4) NOT NULL,
    CONSTRAINT ID_PEDIDO_PK PRIMARY KEY (ID_PEDIDO));

CREATE TABLE LOCALIDADES (
    ID_LOCALIDAD INT(3) NOT NULL AUTO_INCREMENT,
    ID_ESTADO INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_LOCALIDAD_PK PRIMARY KEY (ID_LOCALIDAD));

CREATE TABLE ESTADOS (
    ID_ESTADO INT(3) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_ESTADO_PK PRIMARY KEY (ID_ESTADO));

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT(3) NOT NULL AUTO_INCREMENT,
    ID_DIRECCION INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO INT(10) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT ID_PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR));

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT(3) NOT NULL AUTO_INCREMENT,
    ID_PROVEEDOR INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    EXISTENCIA INT(4) NOT NULL,
    PRECIO FLOAT(6,2) NOT NULL,
    CONSTRAINT ID_PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO));

CREATE TABLE IMAGENES (
    ID_IMAGEN INT(3) NOT NULL AUTO_INCREMENT,
    ID_PRODUCTO INT(3) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    SOURCE BLOB NOT NULL,
    CONSTRAINT ID_IMAGEN_PK PRIMARY KEY (ID_IMAGEN));

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS_DIRECCION
FOREIGN KEY (ID_DIRECCION)
REFERENCES DIRECCIONES(ID_DIRECCION)
ON DELETE CASCADE;

ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOS_ROL
FOREIGN KEY (ID_ROL)
REFERENCES ROLES(ID_ROL)
ON DELETE CASCADE;

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_USUARIOS
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIOS(ID_USUARIO)
ON DELETE CASCADE;

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_PRODUCTOS
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTOS(ID_PRODUCTO)
ON DELETE CASCADE;

ALTER TABLE PROVEEDORES
ADD CONSTRAINT FK_PROVEEDORES_DIRECCION
FOREIGN KEY (ID_DIRECCION)
REFERENCES DIRECCIONES(ID_DIRECCION)
ON DELETE CASCADE;

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOS_PROVEEDORES
FOREIGN KEY (ID_PROVEEDOR)
REFERENCES PROVEEDORES(ID_PROVEEDOR)
ON DELETE CASCADE;

ALTER TABLE DIRECCIONES
ADD CONSTRAINT FK_DIRECCIONES_LOCALIDADES
FOREIGN KEY (ID_LOCALIDAD)
REFERENCES LOCALIDADES(ID_LOCALIDAD)
ON DELETE CASCADE;

ALTER TABLE LOCALIDADES
ADD CONSTRAINT FK_LOCALIDADES_ESTADO
FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADOS(ID_ESTADO)
ON DELETE CASCADE;

ALTER TABLE IMAGENES
ADD FOREIGN KEY (ID_PRODUCTO) 
REFERENCES PRODUCTOS(ID_PRODUCTO)
ON DELETE CASCADE;

ALTER TABLE USUARIOS AUTO_INCREMENT = 100;

ALTER TABLE DIRECCIONES AUTO_INCREMENT = 200;

ALTER TABLE LOCALIDADES AUTO_INCREMENT = 300;

ALTER TABLE ESTADOS AUTO_INCREMENT = 400;

ALTER TABLE ROLES AUTO_INCREMENT = 600;

ALTER TABLE PEDIDOS AUTO_INCREMENT = 500;

ALTER TABLE PROVEEDORES AUTO_INCREMENT = 700;

ALTER TABLE PRODUCTOS AUTO_INCREMENT = 800;

ALTER TABLE IMAGENES AUTO_INCREMENT = 1;

INSERT INTO ESTADOS (NOMBRE) VALUES 
('Aguascalientes'), ('Baja California'), ('Baja California Sur'), ('Campeche'), ('Coahuila'), 
('Colima'), ('Chiapas'), ('Chihuahua'), ('Durango'), ('Guanajuato'), ('Guerrero'), ('Hidalgo'), 
('Jalisco'), ('México'), ('Michoacán'), ('Morelos'), ('Nayarit'), ('Nuevo León'), ('Oaxaca'), 
('Puebla'), ('Querétaro'), ('Quintana Roo'), ('San Luis Potosí'), ('Sinaloa'), ('Sonora'), 
('Tabasco'), ('Tamaulipas'), ('Tlaxcala'), ('Veracruz'), ('Yucatán'), ('Zacatecas');

INSERT INTO LOCALIDADES (ID_ESTADO, NOMBRE) VALUES ('412','Diximoxicity'), ('420', 'Miguel Hidalgo'), ('413', 'San Mateo Atenco');

INSERT INTO DIRECCIONES (ID_LOCALIDAD, DIRECCION, CP) VALUES ('300' , 'Albert Einsten #4035', '80920'), ('301' , 'Fuentes del sol #023', '32400'), ('302' , 'Los ahuehuetes #12', '50235');

INSERT INTO ROLES (NOMBRE) VALUES ('Usuario'), ('Administrador');
